= SBuild Maven Deploy Plugin
:pluginversion: 0.1.0
:sbuildversion: 0.7.1
:toc:
:toc-placement: preamble

This SBuild plugin provides targets to deploy artifacts with the Maven. E.g. you can use it to deploy to Nexus OSS.

== Installation

SBuild Maven Deploy Plugin can be downloaded from http://repo1.maven.org/maven2/org/sbuild/org.sbuild.plugins.mavendeploy/[Maven Central].

To include it in you SBuild buildfile use the `@classpath` annotation:

[source,scala,subs="attributes"]
----
@classpath("mvn:org.sbuild:org.sbuild.plugins.mavendeploy:{pluginversion}")
----

== Building from Source

----
git clone https://github.com/SBuild-org/maven-deploy.git
cd sbuild-sbuild-plugin/org.sbuild.plugins.mavendeploy
sbuild all
----

You will find the built jar in the directory `org.sbuild.plugins.mavendeploy/target`.

== Configuration

All configurable properties are documented via ScalaDoc. See file link:org.sbuild.plugins.mavendeploy/src/main/scala/org/sbuild/plugins/mavendeploy/MavenDeploy.scala[`MavenDeploy`].

== Usage Example

[source,scala,subs="attributes"]
----
import de.tototec.sbuild._

@version("{sbuildversion}")
@classpath("mvn:org.sbuild:org.sbuild.plugins.mavendeploy:{pluginversion}")
class SBuild(implicit _project: Project) {

  import org.sbuild.plugins.mavendeploy._

  Plugin[MavenDeploy] configure { _.copy(
    groupId = "org.example",
    artifactId = "hello",
    version = "1.0.0",
    repository = Repository(id = "nexus", url = "http:://nexus.my-company.local/repo"),
    files = Map(
      "jar" -> "target/hello-1.0.0.jar",
      "sources" -> "target/hello-1.0.0-sources.jar"
    )
  )}

}
----

----
bash$ sbuild -l

----

To deploy the artifacts use the `maven-deploy` target. It is essential, to run sbuild with the `-j 1` option, as the targets are interactive and require user input.

== Changelog

=== SBuild Maven Deploy Plugin 0.1.0 - 2014-01-24

* Initial Release.
